# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anomaly.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""The following code was generated from the Qt Designer. Every
ui_[blank].py file has a correspinding [blank].ui file. We converted
every UI file from PyQt4 to PyQt 5 as part of our upgrades."""


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_anomalyReportDlg(object):
    def setupUi(self, anomalyReportDlg):
        anomalyReportDlg.setObjectName("anomalyReportDlg")
        anomalyReportDlg.resize(261, 67)
        self.widget = QtWidgets.QWidget(anomalyReportDlg)
        self.widget.setGeometry(QtCore.QRect(7, 10, 247, 48))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.viewReportPushButton = QtWidgets.QPushButton(self.widget)
        self.viewReportPushButton.setObjectName("viewReportPushButton")
        self.horizontalLayout.addWidget(self.viewReportPushButton)
        self.printReportPushButton = QtWidgets.QPushButton(self.widget)
        self.printReportPushButton.setObjectName("printReportPushButton")
        self.horizontalLayout.addWidget(self.printReportPushButton)
        self.exitPushButton = QtWidgets.QPushButton(self.widget)
        self.exitPushButton.setObjectName("exitPushButton")
        self.horizontalLayout.addWidget(self.exitPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.statusLabel = QtWidgets.QLabel(self.widget)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)

        self.retranslateUi(anomalyReportDlg)
        QtCore.QMetaObject.connectSlotsByName(anomalyReportDlg)

    def retranslateUi(self, anomalyReportDlg):
        _translate = QtCore.QCoreApplication.translate
        anomalyReportDlg.setWindowTitle(_translate("anomalyReportDlg", "Dialog"))
        self.viewReportPushButton.setText(_translate("anomalyReportDlg", "&View Report"))
        self.printReportPushButton.setText(_translate("anomalyReportDlg", "&Print Report"))
        self.exitPushButton.setText(_translate("anomalyReportDlg", "E&xit"))
        self.statusLabel.setText(_translate("anomalyReportDlg", "(Status)"))
