# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dentistbill.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""The following code was generated from the Qt Designer. Every
ui_[blank].py file has a correspinding [blank].ui file. We converted
every UI file from PyQt4 to PyQt 5 as part of our upgrades."""


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dentistBillDlg(object):
    def setupUi(self, dentistBillDlg):
        dentistBillDlg.setObjectName("dentistBillDlg")
        dentistBillDlg.resize(402, 364)
        self.listWidget = QtWidgets.QListWidget(dentistBillDlg)
        self.listWidget.setGeometry(QtCore.QRect(51, 128, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.printPushButton = QtWidgets.QPushButton(dentistBillDlg)
        self.printPushButton.setGeometry(QtCore.QRect(52, 96, 77, 25))
        self.printPushButton.setObjectName("printPushButton")
        self.cancelPushButton = QtWidgets.QPushButton(dentistBillDlg)
        self.cancelPushButton.setGeometry(QtCore.QRect(135, 96, 77, 25))
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.widget = QtWidgets.QWidget(dentistBillDlg)
        self.widget.setGeometry(QtCore.QRect(51, 62, 217, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.overdueDaysSpinBox = QtWidgets.QSpinBox(self.widget)
        self.overdueDaysSpinBox.setMaximum(360)
        self.overdueDaysSpinBox.setSingleStep(30)
        self.overdueDaysSpinBox.setProperty("value", 30)
        self.overdueDaysSpinBox.setObjectName("overdueDaysSpinBox")
        self.horizontalLayout_2.addWidget(self.overdueDaysSpinBox)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)

        self.retranslateUi(dentistBillDlg)
        QtCore.QMetaObject.connectSlotsByName(dentistBillDlg)

    def retranslateUi(self, dentistBillDlg):
        _translate = QtCore.QCoreApplication.translate
        dentistBillDlg.setWindowTitle(_translate("dentistBillDlg", "Dialog"))
        self.printPushButton.setText(_translate("dentistBillDlg", "&Print"))
        self.cancelPushButton.setText(_translate("dentistBillDlg", "&Cancel"))
        self.pushButton.setText(_translate("dentistBillDlg", "Add &Overdue"))
        self.label.setText(_translate("dentistBillDlg", "by at least"))
        self.label_2.setText(_translate("dentistBillDlg", "days"))
