# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'overduereport.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""The following code was generated from the Qt Designer. Every
ui_[blank].py file has a correspinding [blank].ui file. We converted
every UI file from PyQt4 to PyQt 5 as part of our upgrades."""


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_overdueReportDlg(object):
    def setupUi(self, overdueReportDlg):
        overdueReportDlg.setObjectName("overdueReportDlg")
        overdueReportDlg.resize(261, 100)
        self.widget = QtWidgets.QWidget(overdueReportDlg)
        self.widget.setGeometry(QtCore.QRect(11, 11, 247, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.daysOverdueSpinBox = QtWidgets.QSpinBox(self.widget)
        self.daysOverdueSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.daysOverdueSpinBox.setMinimum(0)
        self.daysOverdueSpinBox.setMaximum(360)
        self.daysOverdueSpinBox.setSingleStep(30)
        self.daysOverdueSpinBox.setProperty("value", 0)
        self.daysOverdueSpinBox.setObjectName("daysOverdueSpinBox")
        self.horizontalLayout.addWidget(self.daysOverdueSpinBox)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.renewalOnlyCheckBox = QtWidgets.QCheckBox(self.widget)
        self.renewalOnlyCheckBox.setObjectName("renewalOnlyCheckBox")
        self.verticalLayout.addWidget(self.renewalOnlyCheckBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewReportPushButton = QtWidgets.QPushButton(self.widget)
        self.viewReportPushButton.setObjectName("viewReportPushButton")
        self.horizontalLayout_2.addWidget(self.viewReportPushButton)
        self.printReportPushButton = QtWidgets.QPushButton(self.widget)
        self.printReportPushButton.setObjectName("printReportPushButton")
        self.horizontalLayout_2.addWidget(self.printReportPushButton)
        self.exitPushButton = QtWidgets.QPushButton(self.widget)
        self.exitPushButton.setObjectName("exitPushButton")
        self.horizontalLayout_2.addWidget(self.exitPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(overdueReportDlg)
        QtCore.QMetaObject.connectSlotsByName(overdueReportDlg)

    def retranslateUi(self, overdueReportDlg):
        _translate = QtCore.QCoreApplication.translate
        overdueReportDlg.setWindowTitle(_translate("overdueReportDlg", "Dialog"))
        self.label.setText(_translate("overdueReportDlg", "Billed at least"))
        self.label_2.setText(_translate("overdueReportDlg", "days ago"))
        self.renewalOnlyCheckBox.setText(_translate("overdueReportDlg", "Only Accounts needing Renewal"))
        self.viewReportPushButton.setText(_translate("overdueReportDlg", "&View Report"))
        self.printReportPushButton.setText(_translate("overdueReportDlg", "&Print Report"))
        self.exitPushButton.setText(_translate("overdueReportDlg", "E&xit"))
