# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""The following code was generated from the Qt Designer. Every
ui_[blank].py file has a correspinding [blank].ui file. We converted
every UI file from PyQt4 to PyQt 5 as part of our upgrades."""


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_reportDlg(object):
    def setupUi(self, reportDlg):
        reportDlg.setObjectName("reportDlg")
        reportDlg.resize(142, 252)
        self.widget = QtWidgets.QWidget(reportDlg)
        self.widget.setGeometry(QtCore.QRect(10, 13, 120, 229))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dailyPaymentReportPushButton = QtWidgets.QPushButton(self.widget)
        self.dailyPaymentReportPushButton.setObjectName("dailyPaymentReportPushButton")
        self.verticalLayout_3.addWidget(self.dailyPaymentReportPushButton)
        self.testCountPushButton = QtWidgets.QPushButton(self.widget)
        self.testCountPushButton.setObjectName("testCountPushButton")
        self.verticalLayout_3.addWidget(self.testCountPushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.overdueAccountsPushButton = QtWidgets.QPushButton(self.widget)
        self.overdueAccountsPushButton.setObjectName("overdueAccountsPushButton")
        self.verticalLayout_2.addWidget(self.overdueAccountsPushButton)
        self.activityReportPushButton = QtWidgets.QPushButton(self.widget)
        self.activityReportPushButton.setObjectName("activityReportPushButton")
        self.verticalLayout_2.addWidget(self.activityReportPushButton)
        self.anomalyReportPushButton = QtWidgets.QPushButton(self.widget)
        self.anomalyReportPushButton.setObjectName("anomalyReportPushButton")
        self.verticalLayout_2.addWidget(self.anomalyReportPushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.quarterlyPaymentSummaryPushButton = QtWidgets.QPushButton(self.widget)
        self.quarterlyPaymentSummaryPushButton.setObjectName("quarterlyPaymentSummaryPushButton")
        self.verticalLayout.addWidget(self.quarterlyPaymentSummaryPushButton)
        self.yearlyCompliancePushButton = QtWidgets.QPushButton(self.widget)
        self.yearlyCompliancePushButton.setObjectName("yearlyCompliancePushButton")
        self.verticalLayout.addWidget(self.yearlyCompliancePushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.lotRecallPushButton = QtWidgets.QPushButton(self.widget)
        self.lotRecallPushButton.setObjectName("lotRecallPushButton")
        self.verticalLayout_4.addWidget(self.lotRecallPushButton)

        self.retranslateUi(reportDlg)
        QtCore.QMetaObject.connectSlotsByName(reportDlg)

    def retranslateUi(self, reportDlg):
        _translate = QtCore.QCoreApplication.translate
        reportDlg.setWindowTitle(_translate("reportDlg", "Dialog"))
        self.dailyPaymentReportPushButton.setText(_translate("reportDlg", "Daily &Payment"))
        self.testCountPushButton.setText(_translate("reportDlg", "Daily &Test Count"))
        self.overdueAccountsPushButton.setText(_translate("reportDlg", "Outstanding &Balances"))
        self.activityReportPushButton.setText(_translate("reportDlg", "Activity Report"))
        self.anomalyReportPushButton.setText(_translate("reportDlg", "&Anomaly Report"))
        self.quarterlyPaymentSummaryPushButton.setText(_translate("reportDlg", "Accounts &Summary"))
        self.yearlyCompliancePushButton.setText(_translate("reportDlg", "Yearly &Compliance"))
        self.lotRecallPushButton.setText(_translate("reportDlg", "Lot &Recall"))
