# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'starttest.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""The following code was generated from the Qt Designer. Every
ui_[blank].py file has a correspinding [blank].ui file. We converted
every UI file from PyQt4 to PyQt 5 as part of our upgrades."""


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startTestDlg(object):
    def setupUi(self, startTestDlg):
        startTestDlg.setObjectName("startTestDlg")
        startTestDlg.resize(283, 121)
        self.formLayout = QtWidgets.QFormLayout(startTestDlg)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(startTestDlg)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.testNumLineEdit = QtWidgets.QLineEdit(startTestDlg)
        self.testNumLineEdit.setObjectName("testNumLineEdit")
        self.verticalLayout.addWidget(self.testNumLineEdit)
        spacerItem = QtWidgets.QSpacerItem(18, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.confirmPushButton = QtWidgets.QPushButton(startTestDlg)
        self.confirmPushButton.setObjectName("confirmPushButton")
        self.horizontalLayout.addWidget(self.confirmPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(startTestDlg)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)

        self.retranslateUi(startTestDlg)
        QtCore.QMetaObject.connectSlotsByName(startTestDlg)

    def retranslateUi(self, startTestDlg):
        _translate = QtCore.QCoreApplication.translate
        startTestDlg.setWindowTitle(_translate("startTestDlg", "Dialog"))
        self.label.setText(_translate("startTestDlg", "Please Enter Test Identification Number for New Test:"))
        self.confirmPushButton.setText(_translate("startTestDlg", "Confirm"))
        self.cancelPushButton.setText(_translate("startTestDlg", "Cancel"))
