# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sendrenewal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""The following code was generated from the Qt Designer. Every
ui_[blank].py file has a correspinding [blank].ui file. We converted
every UI file from PyQt4 to PyQt 5 as part of our upgrades."""


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sendRenewalDlg(object):
    def setupUi(self, sendRenewalDlg):
        sendRenewalDlg.setObjectName("sendRenewalDlg")
        sendRenewalDlg.resize(373, 134)
        self.widget = QtWidgets.QWidget(sendRenewalDlg)
        self.widget.setGeometry(QtCore.QRect(11, 11, 355, 113))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.renewalIdLineEdit = QtWidgets.QLineEdit(self.widget)
        self.renewalIdLineEdit.setObjectName("renewalIdLineEdit")
        self.horizontalLayout.addWidget(self.renewalIdLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.numRenewalsLineEdit = QtWidgets.QLineEdit(self.widget)
        self.numRenewalsLineEdit.setEnabled(False)
        self.numRenewalsLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.numRenewalsLineEdit.setObjectName("numRenewalsLineEdit")
        self.horizontalLayout_2.addWidget(self.numRenewalsLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.printMailingLabelsPushButton = QtWidgets.QPushButton(self.widget)
        self.printMailingLabelsPushButton.setObjectName("printMailingLabelsPushButton")
        self.horizontalLayout_3.addWidget(self.printMailingLabelsPushButton)
        self.printReportsPushButton = QtWidgets.QPushButton(self.widget)
        self.printReportsPushButton.setObjectName("printReportsPushButton")
        self.horizontalLayout_3.addWidget(self.printReportsPushButton)
        self.exitPushButton = QtWidgets.QPushButton(self.widget)
        self.exitPushButton.setObjectName("exitPushButton")
        self.horizontalLayout_3.addWidget(self.exitPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.statusLabel = QtWidgets.QLabel(self.widget)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_4.addWidget(self.statusLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(sendRenewalDlg)
        QtCore.QMetaObject.connectSlotsByName(sendRenewalDlg)

    def retranslateUi(self, sendRenewalDlg):
        _translate = QtCore.QCoreApplication.translate
        sendRenewalDlg.setWindowTitle(_translate("sendRenewalDlg", "Dialog"))
        self.label.setText(_translate("sendRenewalDlg", "Enter Renewal ID:"))
        self.label_2.setText(_translate("sendRenewalDlg", "Current Number of Renewals:"))
        self.printMailingLabelsPushButton.setText(_translate("sendRenewalDlg", "Print &Mailing Labels"))
        self.printReportsPushButton.setText(_translate("sendRenewalDlg", "Print &Reports"))
        self.exitPushButton.setText(_translate("sendRenewalDlg", "E&xit"))
        self.statusLabel.setText(_translate("sendRenewalDlg", "Status Label"))
